# Generated by Django 2.0.2 on 2018-08-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('post_dt', models.DateTimeField()),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
    ]
