# Generated by Django 2.0.2 on 2018-08-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='header_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='post_dt',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default='This is blog post.'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
